name: release
on:
  release:
    types:
      - created

jobs:
  build-release:
    name: build-release (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        include:
          - os: macos-11
            target: x86_64-apple-darwin
          - os: macos-11
            target: aarch64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Tar release (unix)
        working-directory: ./target/${{ matrix.target }}/release
        run: tar cvfz repo-${{matrix.target}}.tar.gz "repo"

      - name: Upload release archive (linux)
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/repo-${{matrix.target}}.tar.gz
